#!/bin/bash

gcp_EnableApis() {

    ## Habilitamos las API para el Proyecto

        # Network API
        gcloud --project $PROJECT_ID services enable servicenetworking.googleapis.com
        
        # Compute API
        gcloud --project $PROJECT_ID services enable compute.googleapis.com

        # Kubernetes API
        gcloud --project $PROJECT_ID services enable container.googleapis.com

        # OpenVPN
        # https://console.cloud.google.com/marketplace/product/openvpn-access-server-200800/openvpn-access-server?hl=es&project=poc-ecommerce30
        gcloud --project $PROJECT_ID services enable deploymentmanager.googleapis.com   # Cloud Deployment Manager V2 API
        gcloud --project $PROJECT_ID services enable runtimeconfig.googleapis.com       # Cloud Runtime Configuration API
}

