#!/bin/bash

gcp_roleOwner(){
    ## Asignamos un role al service account (Owner)
    gcloud projects add-iam-policy-binding $PROJECT_ID --member="serviceAccount:$SERVICE_ACCOUNT_ID@$PROJECT_ID.iam.gserviceaccount.com" --role="roles/owner"
}

gcp_roleResourceManager(){
    ## Asignamos un role al service account (Projec Creator)
    gcloud projects add-iam-policy-binding $PROJECT_ID --member="serviceAccount:$SERVICE_ACCOUNT_ID@$PROJECT_ID.iam.gserviceaccount.com" --role="roles/resourcemanager.projectCreator"    
}

gcp_roleCloudSQL(){
    ## Asignamos un role al service account (Cloud SQL)
    gcloud projects add-iam-policy-binding $PROJECT_ID --member="serviceAccount:$SERVICE_ACCOUNT_ID@$PROJECT_ID.iam.gserviceaccount.com" --role="roles/cloudsql.admin"
}

gpc_roleVPCaccess(){
    ## Asignamos un role al service account (Serverless VPC Access)
    gcloud projects add-iam-policy-binding $PROJECT_ID --member="serviceAccount:$SERVICE_ACCOUNT_ID@$PROJECT_ID.iam.gserviceaccount.com" --role="roles/vpcaccess.admin"
}

gcp_roleViewer(){    
    ## Asignamos un role al service account (viewer) 
    gcloud projects add-iam-policy-binding $PROJECT_ID --member="serviceAccount:$SERVICE_ACCOUNT_ID@$PROJECT_ID.iam.gserviceaccount.com" --role="roles/viewer"
}