#!/bin/bash

gcp_EnableApis() {

    # Cargamos libreria de mensajes.
        source ./showMessage

    ## Habilitamos las API para el Proyecto

        showMessage "Network API"
        gcloud --project $PROJECT_ID services enable servicenetworking.googleapis.com
        
        showMessage "Compute API"
        gcloud --project $PROJECT_ID services enable compute.googleapis.com

        showMessage "Kubernetes API"
        gcloud --project $PROJECT_ID services enable container.googleapis.com

        showMessage "OpenVPN"
        # https://console.cloud.google.com/marketplace/product/openvpn-access-server-200800/openvpn-access-server?hl=es&project=poc-ecommerce30
        gcloud --project $PROJECT_ID services enable deploymentmanager.googleapis.com   # Cloud Deployment Manager V2 API
        gcloud --project $PROJECT_ID services enable runtimeconfig.googleapis.com       # Cloud Runtime Configuration API

        showMessage "ServerLess (Cloud SQL for MySQL)"
        gcloud --project $PROJECT_ID services enable servicenetworking.googleapis.com
        gcloud --project $PROJECT_ID services enable sqladmin.googleapis.com
}