#!/bin/bash

gcp_EnableRoles(){

## Cargamos libreria de mensaje
. ./func/showMessage

    showMessage "Asignamos role al service account (Owner)"
    gcloud projects add-iam-policy-binding $PROJECT_ID --member="serviceAccount:$SERVICE_ACCOUNT_ID@$PROJECT_ID.iam.gserviceaccount.com" --role="roles/owner"

    showMessage "Asignamos role al service accoun (Cloud SQL Admin)"
    gcloud projects add-iam-policy-binding $PROJECT_ID --member="serviceAccount:$SERVICE_ACCOUNT_ID@$PROJECT_ID.iam.gserviceaccount.com" --role="roles/cloudsql.admin"  

    showMessage "Asignamos role al service accoun (VPC Access Admin)"
    gcloud projects add-iam-policy-binding $PROJECT_ID --member="serviceAccount:$SERVICE_ACCOUNT_ID@$PROJECT_ID.iam.gserviceaccount.com" --role="roles/vpcaccess.admin"

    showMessage "Asignamos role al service account (Viewer)"
    gcloud projects add-iam-policy-binding $PROJECT_ID --member="serviceAccount:$SERVICE_ACCOUNT_ID@$PROJECT_ID.iam.gserviceaccount.com" --role="roles/viewer"
}