#!/bin/bash

installGcloud(){

# Verificamos si esta instalado
if ! command -v gcloud &> /dev/null
then
    echo ""
    echo "###################################"
    echo "Google Cloud SDK no esta Instalado"
    echo "###################################"
    echo ""
    
    curl https://sdk.cloud.google.com > install.sh
    bash install.sh --disable-prompts

    echo ""
    echo "###################################"
    echo "    Se instalo Google Cloud SDK"
    echo "###################################"
    echo ""

    # Agregamos el comando gcloud al ~/.bashrc
    echo "source /root/google-cloud-sdk/completion.bash.inc" >> ~/.bashrc
    echo "source /root/google-cloud-sdk/path.bash.inc" >> ~/.bashrc

else
    echo ""
    echo "###############################"
    echo "Google Cloud SDK esta Instalado"
    echo "###############################"
    echo ""
fi
}