#!/bin/bash

gcp_gcloudSDK(){

# Cargamos las librerias
. ./func/checkOS
. ./func/installDependencies
. ./func/installGcloud

# Verificamos OS y Plataformas
checkOS

# Instalamos Dependencias
install_Dependencies

# Instalamos Google Cloud SDK
installGcloud
}



