#!/bin/bash

#curl https://sdk.cloud.google.com | bash
#exec -l $SHELL
#gcloud init --quiet

### EXAMPLE:
#[root@gsv-gastion terraform-gcp]# gcloud auth application-default login  --no-launch-browser
#Go to the following link in your browser:
#
#    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=111111111111111111111.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Faccounts.reauth&state=5O4mgljELpd5aNu23k9FZt21z3ftD1&prompt=consent&access_type=offline&code_challenge=dEjR5kYMjFQDFmJrFNk9NUi-vrMDDZLAy4hQxaStGTQ&code_challenge_method=S256

#Enter verification code:

# Logeamos nuesta cuenta.
gcp_login() {
gcloud auth application-default login --no-launch-browser
}

# Deslogueamos la cuenta actual por precaucion.
gcp_logout(){
    gcloud auth revoke --all
}

